url: "http://pangnate.com"
permalink: "/:year/:month/:day/:title"
paginate: 2
paginate_path: "/page/:num"
asset_path: "/asset"
uploads_path: "/uploads"
timezone: "Asia/Shanghai"
author: '<a href="http://weibo.com/pangnate" target="_blank" rel="nofollow">pangnate</a>'
excerpt_separator: '<!--more-->'
title: '胖纳特的blog'
version: '2014010401'
